[package]
name = "music-assistant-desktop"
version = "0.0.12"
description = "Music Assistant Desktop App"
authors = ["you"]
license = "Apache-2.0"
repository = "https://github.com/Un10ck3d/massapp"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = [ "dialog-message", "updater", "shell-sidecar", "shell-open", "process-command-api", "devtools", "config-toml"] }
discord-rich-presence = "0.2.3"
tungstenite = {version = "0.19.0", features = ["native-tls"] }
url = "2.4.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
gethostname = "0.4.3"
tauri-plugin-localhost = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
