[build]
beforeDevCommand = "cd frontend-source && yarn dev"
beforeBuildCommand = "cd frontend-source/ && yarn && yarn build"
devPath = "http://localhost:1420"
distDir = "../frontend-source/dist"
withGlobalTauri = false

[package]
productName = "mass"
version = "0.0.3"

[tauri.allowlist]
all = false

[tauri.allowlist.dialog]
all = true

[tauri.allowlist.shell]
all = false
open = true
sidecar = true

[[tauri.allowlist.shell.scope]]
name = "squeezelite"
sidecar = true
args = true

[tauri.bundle]
active = true
targets = "all"
identifier = "com.mass.app"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
externalBin = [ "binaries/squeezelite" ]

[tauri.bundle.appimage]
bundleMediaFramework = true

[tauri.bundle.macOS]
entitlements = "Entitlements.plist"
minimumSystemVersion = 11.3

[tauri.security]

[[tauri.windows]]
fullscreen = false
resizable = true
title = "Mass Desktop"
width = 800
height = 600

[tauri.updater]
active = true
dialog = false
pubkey = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IERDRTNDNDM0NEE5NzQyQjcKUldTM1FwZEtOTVRqM0JCWFhNU3oyZDIyTmpFbStPQjF1bXBqaWNrQkZFN1V3c25SMVArOVN1WFoK"

[tauri.updater.windows]
installMode = "passive"
